### ISSUE TITLE
 deserialize_cuda_engine

### ISSUE THREAD

**Issue by YijiaZhao** [shiyongming/Segmentation-models-benchmark#1]
trt_infer.py will deserialize_cuda_engine trt engine in every inference time, I rewrite TensorRTInfer as follows:

    def __init__(self, engine_path):
        self.logger = trt.Logger(trt.Logger.ERROR)
        trt.init_libnvinfer_plugins(self.logger, namespace="")
        with open(engine_path, "rb") as f, trt.Runtime(self.logger) as runtime:
            self.engine = runtime.deserialize_cuda_engine(f.read())
        
        self.context = self.engine.create_execution_context()
        self.context.active_optimization_profile = 0

    def set_bind_shape(self, shape):    
       ...

**Comment by shiyongming** [comment]
thanks YijiaZhao!

**Comment by YijiaZhao** [comment]
[trt_infer.py.txt](https://github.com/shiyongming/Segmentation-models-benchmark/files/8897830/trt_infer.py.txt)
I use this script to measure the time of TRT and PYTORCH, INT8 TRT is 60% faster than Torch(H2D(input) + inference time)
